services:
  frontend:
    build:
      context: ./client
      dockefile: dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
  nodebackend:
    build:
      context: ./server
      dockerfile: Dockerfile.node
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - '27018:27017'
